// js/smart-launch.js

// Global Fail-Safe block
if (typeof SMART_CONFIG === "undefined") {
    window.SMART_CONFIG = {
        CLIENT_ID: "ef3b2af6-c1b8-4421-9dda-108c6ac8afce",
        
        // FIXED: Hardcoded string safely duplicated here to prevent mismatch bugs
        REDIRECT_URI: "gstank01.github.io/smart-on-fhir-app/index.html", 
        
        ENDPOINTS: {
            EPIC_AUTHORIZE: "https://vendorservices.epic.com/interconnect-amcurprd-oauth/oauth2/authorize",
            EPIC_TOKEN: "https://vendorservices.epic.com/interconnect-amcurprd-oauth/oauth2/token"
        },
        SCOPES: "launch openid fhirUser"
    };
}

async function executeSmartLaunch() {
    const urlParams = new URLSearchParams(window.location.search);
    const statusDiv = document.getElementById("status");
    if (!statusDiv) return;

    if (urlParams.has("iss") && urlParams.has("launch")) {
        const fhirServerUrl = urlParams.get("iss");
        const launchToken = urlParams.get("launch");

        statusDiv.className = "";
        statusDiv.innerHTML = `
            <div class="inspection-card">
                <h4>Step 1: Launch Parameters Caught Successfully!</h4>
                <p class="inspect-label">1. Full URL generated by the Simulator:</p>
                <code class="inspect-code url">${window.location.href}</code>
                <p class="inspect-label">2. Extracted FHIR Endpoint (iss):</p>
                <code class="inspect-code iss">${fhirServerUrl}</code>
                <p class="inspect-label">3. Extracted Session Token (launch):</p>
                <div class="inspect-scroll-box">${launchToken}</div>
                <button id="proceed-to-inspect-btn" class="proceed-btn">All looks good → Proceed to Request Preview</button>
            </div>
        `;

        document.getElementById("proceed-to-inspect-btn").addEventListener("click", function () {
            handleLaunchPhase(fhirServerUrl, launchToken);
        });
    } else {
        statusDiv.className = "error-message";
        statusDiv.innerHTML = `
            <strong>Error: Missing launch parameters in URL.</strong><br>
            <span style="font-size:12px; color:#7f8c8d;">Please start the application workspace flow container from the Epic Simulator.</span>
        `;
    }
}

function handleLaunchPhase(fhirServerUrl, launchToken) {
    sessionStorage.setItem("fhirServerUrl", fhirServerUrl);

    // Secure state generation with math random fallback for local testing frames
    let secureState = (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") 
        ? crypto.randomUUID() 
        : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
            const r = Math.random() * 16 | 0; return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
          });
    sessionStorage.setItem("expectedState", secureState);

    // 1. Construct the precise payload matching your working POST schema
    const params = {
        scope: SMART_CONFIG.SCOPES, // Scopes configured per your environment configuration
        response_type: "code",
        redirect_uri: SMART_CONFIG.REDIRECT_URI, // Character-for-character registered callback string
        client_id: SMART_CONFIG.CLIENT_ID,
        launch: launchToken, // Stored launch token
        state: secureState, // Unique transaction key generated above
        aud: fhirServerUrl // The base URL of the resource server we intend to query
      };

    const formUrlEncodedBody = new URLSearchParams(params).toString();

    // 2. Assemble accurate absolute raw HTTP POST preview string
    let rawHttpText = `POST ${SMART_CONFIG.ENDPOINTS.EPIC_AUTHORIZE} HTTP/1.1\n`;
    rawHttpText += `Host: vendorservices.epic.com\n`;
    rawHttpText += `Content-Type: application/x-www-form-urlencoded\n`;
    rawHttpText += `Connection: keep-alive\n\n`;
    rawHttpText += formUrlEncodedBody;

    // 3. Render the preview UI dashboard panel using clean CSS classes
    document.getElementById("status").innerHTML = `
        <h4 class="preview-title">Raw HTTP POST Request Preview:</h4>
        <p class="preview-desc">Review the POST request payload sent to Epic:</p>
        <textarea readonly class="raw-http-box">${rawHttpText}</textarea>
        <p class="success-note">Form parameters compiled and URL-encoded successfully.</p>
        <button id="submit-to-epic-btn" class="epic-submit-btn">Send HTTP POST to Epic Authorization Server →</button>
    `;

    // 4. Manually assemble the structural hidden HTML form element
    const nativeForm = document.createElement("form");
    nativeForm.method = "POST";
    nativeForm.action = SMART_CONFIG.ENDPOINTS.EPIC_AUTHORIZE;
    nativeForm.target = "_top"; // Escapes iframe limitations cleanly
    nativeForm.style.display = "none";

    for (const [key, value] of Object.entries(params)) {
        const hiddenField = document.createElement("input");
        hiddenField.type = "hidden";
        hiddenField.name = key;
        hiddenField.value = value;
        nativeForm.appendChild(hiddenField);
    }
    document.body.appendChild(nativeForm);

        // 5. Fire form submission on button confirmation click
    document.getElementById("submit-to-epic-btn").addEventListener("click", function (event) {
        event.preventDefault(); // Halt transmission loop temporarily for logging

        // EXTRCTION 1: Log the raw HTML element block structure directly
        console.log("--- RAW HTML FORM ELEMENT ---");
        console.log(nativeForm); 

        // EXTRACTION 2: Extract and view it as a neat, interactive key-value JSON object
        console.log("--- FORM PAYLOAD DATA OBJECT ---");
        const formData = new FormData(nativeForm); // Reads all input name/value pairs
        const plainPayloadObject = Object.fromEntries(formData); // Flattens it
        console.table(plainPayloadObject); // Prints a beautiful debugging matrix grid

        document.getElementById("status").innerText = "Transmitting POST request payload natively via browser context...";
        
        // Execute the real transmission out to Epic
        nativeForm.submit(); 
    });

}

document.addEventListener("DOMContentLoaded", executeSmartLaunch);
