// js/smart-launch.js

async function executeSmartLaunch() {
    
    //extract query parameters from the browser's address bar and ensure a specific HTML element exists before running further code.
    //window.location.search grabs the query string from the URL (everything starting from the ?)
    //URLSearchParams converts the string into an easy-to-use object. This allows to quickly fetch specific values later
    const urlParams = new URLSearchParams(window.location.search);
    const statusDiv = document.getElementById("status"); //grabs the container where mesages will be displayed
    if (!statusDiv) return; //abort if empty

    //check urlParams and set the variables to store the launch and iss paramtres from the email
    if (urlParams.has("iss") && urlParams.has("launch")) {
        const fhirServerUrl = urlParams.get("iss");
        const launchToken = urlParams.get("launch");

        statusDiv.className = ""; //reset any CSS styles already set on the page 

        //set the contasiner to display Step one of the workflow
        
        statusDiv.innerHTML = ` 
            <div class="inspection-card">
                <h4>Step 1: Launch Parameters Caught Successfully!</h4>
                <p class="inspect-label">1. Full URL generated by the Simulator(EPIC EHR in real world scenarios). Upon clicking on the link embeded in the EHR UI, Epic appends the launch and iss parametres after the base URL. Our job is to catch those parametres and use when constructing our HTTP POST or GET request to obtain the Authorization Code</p>
                <code class="inspect-code url">${window.location.href}</code> <!-- window.location.href allows to display the full url from the browser -->
                <p class="inspect-label">2. Extracted FHIR Endpoint (iss):</p>
                <code class="inspect-code iss">${fhirServerUrl}</code>
                <p class="inspect-label">3 Extracted Session Token (launch):</p>
                <div class="inspect-scroll-box">${launchToken}</div>
                <button id="proceed-to-inspect-btn" class="proceed-btn">All looks good → Proceed to Request Preview</button>
            </div>
        `;

        //upon clicking the button, the next function is executed
        document.getElementById("proceed-to-inspect-btn").addEventListener("click", function () {
            handleLaunchPhase(fhirServerUrl, launchToken);
        });
    } else {
        statusDiv.className = "error-message";
        statusDiv.innerHTML = `
            <strong>Error: Missing launch parameters in URL.</strong><br>
            <span style="font-size:12px; color:#7f8c8d;">Please start the application workspace flow container from the Epic Simulator.</span>
        `;
    }
}

//This function handles tha launch phase

function handleLaunchPhase(fhirServerUrl, launchToken) { //pass the fhir server url and launch token from the launch function as parametres
    sessionStorage.setItem("fhirServerUrl", fhirServerUrl); //temporarily store the value of that variable inside the browser's memory, linked to a specific label

    // Secure state generation with math random fallback for local testing frames
    // https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
    let secureState = (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") 
        ? crypto.randomUUID() 
        : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { //https://stackoverflow.com/questions/49485073/detailed-explanation-for-this-function-needed
            const r = Math.random() * 16 | 0; return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
          });
    sessionStorage.setItem("expectedState", secureState);

    // 1. Construct the precise payload matching the working POST schema
    const params = {
        scope: SMART_CONFIG.SCOPES, // Scopes configured at config.js
        response_type: "code",
        redirect_uri: SMART_CONFIG.REDIRECT_URI, // Character-for-character registered callback string
        client_id: SMART_CONFIG.CLIENT_ID, //the client ID registered with the Vendor Services website and defined in config.js
        launch: launchToken, // Stored launch token
        state: secureState, // Unique transaction key generated above
        aud: fhirServerUrl // The base URL of the resource server we intend to query
      };

    //format the parametres into a string to be sent cleanly to the server over the internet
    const formUrlEncodedBody = new URLSearchParams(params).toString();

    // 2. Assemble accurate  raw HTTP POST preview string
    let rawHttpText = `POST ${SMART_CONFIG.ENDPOINTS.EPIC_AUTHORIZE} HTTP/1.1\n`;
    rawHttpText += `Host: vendorservices.epic.com\n`;
    rawHttpText += `Content-Type: application/x-www-form-urlencoded\n`;
    rawHttpText += `Connection: keep-alive\n\n`;
    rawHttpText += formUrlEncodedBody;

    // 3. Render the preview UI dashboard panel using clean CSS classes
    document.getElementById("status").innerHTML = `
        <h4 class="preview-title">Raw HTTP POST Request Preview:</h4>
        <p class="preview-desc">Review the POST request payload sent to Epic:</p>
        <textarea readonly class="raw-http-box">${rawHttpText}</textarea>
        <p class="success-note">Form parameters compiled and URL-encoded successfully.</p>
        <button id="submit-to-epic-btn" class="epic-submit-btn">Send HTTP POST to Epic Authorization Server →</button>
    `;

    // 4. Manually assemble the structural hidden HTML form element
    const nativeForm = document.createElement("form");
    nativeForm.method = "POST";
    nativeForm.action = SMART_CONFIG.ENDPOINTS.EPIC_AUTHORIZE;
    nativeForm.target = "_top"; // Escapes iframe limitations cleanly
    nativeForm.style.display = "none";

    for (const [key, value] of Object.entries(params)) {
        const hiddenField = document.createElement("input");
        hiddenField.type = "hidden";
        hiddenField.name = key;
        hiddenField.value = value;
        nativeForm.appendChild(hiddenField);
    }
    document.body.appendChild(nativeForm);

        // 5. Fire form submission on button confirmation click
    document.getElementById("submit-to-epic-btn").addEventListener("click", function (event) {
        event.preventDefault(); // Halt transmission loop temporarily for logging

        document.getElementById("status").innerText = "Transmitting POST request payload natively via browser context...";
        
        // Execute the real transmission out to Epic
        nativeForm.submit(); 
    });

}

//Wait for your webpage to finish loading its structure before automatically starting the SMART on FHIR login process
document.addEventListener("DOMContentLoaded", executeSmartLaunch);
