// js/smart-launch.js
async function executeSmartLaunch() {
    const urlParams = new URLSearchParams(window.location.search);
    const statusDiv = document.getElementById("status");

    if (!statusDiv) return;

    // Detect initial launch sequence & inspect variables
    if (urlParams.has("iss") && urlParams.has("launch")) {
        const fhirServerUrl = urlParams.get("iss");
        const launchToken = urlParams.get("launch");

        // Render the clean layout using CSS classes instead of inline styles
        statusDiv.className = ""; // Remove the .loading class wrapper
        statusDiv.innerHTML = `
            <div class="inspection-card">
                <h4>Step 1: Launch Parameters Caught Successfully!</h4>
                
                <p class="inspect-label">1. Full URL generated by the Simulator app upon triggering the request:</p>
                <code class="inspect-code url">${window.location.href}</code>
                
                <p class="inspect-label">2. Extracted FHIR Endpoint (iss):</p>
                <code class="inspect-code iss">${fhirServerUrl}</code>
                
                <p class="inspect-label">3. Extracted Session Token (launch):</p>
                <div class="inspect-scroll-box">${launchToken}</div>
                
                <button id="proceed-to-inspect-btn" class="proceed-btn">
                    All looks good → Exchange the launch token for authorization code
                </button>
            </div>
        `;

        // Bind event listener to proceed with the redirect to Epic's login screen
        document.getElementById("proceed-to-inspect-btn").addEventListener("click", function () {
            handleLaunchPhase(fhirServerUrl, launchToken);
        });
    } 
    // If someone visits launch.html manually without the Epic Simulator
    else {
        statusDiv.className = "error-message";
        statusDiv.innerHTML = `
            <strong>Error: Missing launch parameters in URL.</strong><br>
            <span style="font-size:12px; color:#7f8c8d;">Please start the application workspace flow container from the Epic Simulator.</span>
        `;
    }
}

function handleLaunchPhase(fhirServerUrl, launchToken) {
    // Preserve transaction parameters across the redirect hop in local session variables
    sessionStorage.setItem("fhirServerUrl", fhirServerUrl);

    // Generate secure state session tracker (Epic recommendation: UUID for entropy)
    const secureState = crypto.randomUUID();
    sessionStorage.setItem("expectedState", secureState);

    // Construct the parameters using our unified global config asset file
    const authorizeParams = new URLSearchParams({
        response_type: "code",
        client_id: SMART_CONFIG.CLIENT_ID,
        redirect_uri: SMART_CONFIG.REDIRECT_URI,
        launch: launchToken,
        scope: SMART_CONFIG.SCOPES,
        state: secureState,
        aud: fhirServerUrl
    });

    // Execute hand-off to Epic identity server
    window.location.href = `${SMART_CONFIG.ENDPOINTS.EPIC_AUTHORIZE}?${authorizeParams.toString()}`;
}

// Automatically fire when the hosting DOM finishes loading
document.addEventListener("DOMContentLoaded", executeSmartLaunch);
